package com.paysafecard.merchant;

public class ErrorCode {

	public static String getMessage(int code, String cid,  String tid,  String amount,  String currency) {
		
		String msg = "Error "+code;
		if (code==1) msg="No data selected.";
		if (code==2) msg="%1 is not numeric.";
		if (code==3) msg="Mandatory field %1 is empty.";
		if (code==4) msg="Decimal field with name %1 and value %2 has no decimal point.";
		if (code==5) msg="Decimal field with name %1 and value %2 has no digits before the decimal point.";
		if (code==6) msg="Decimal field with name %1 and value %2 has too many digits before the decimal point (max. %3 allowed).";
		if (code==7) msg="Decimal field with name %1 and value %2 has too few digits after the decimal point (must have %3).";
		if (code==8) msg="Decimal field with name %1 and value %2 has too many digits after the decimal point (max. %3 allowed).";
		if (code==9) msg="Decimal field with name %1 and value %2 is not a number with format N.M (where N are 1 to %3 digits, M are exactly %4 digits and M and N are numeric).";
		if (code==10) msg="Decimal field with name %1 and value %2 has no digits after the decimal point (must have at least 1 and at most %3).";
		if (code==11) msg="Decimal field with name %1 and value %2 must not be negative.";
		if (code==12) msg="Decimal field with name %1 and value %2 is not a number with format N.M (where N are 1 to %3 digits, M are 1 to %4 digits and M and N are numeric).";
		if (code==13) msg="Decimal field with name %1 is empty.";
		if (code==14) msg="Cannot process more than %1 objects per transaction.";
		if (code==15) msg="Answer to Challenge Question is empty.";
		if (code==16) msg="Answer to Challenge Question is wrong.";
		if (code==17) msg="Answer to Challenge Question contains invalid characters.";
		if (code==20) msg="Challenge Question is empty.";
		if (code==21) msg="Challenge Question with value %1 is too long (max. %2 characters are allowed).";
		if (code==50) msg="Merchant ID is empty.";
		if (code==51) msg="Merchant ID with value %1 is too long (max. %2 characters are allowed).";
		if (code==55) msg="Merchant-transaction ID is empty.";
		if (code==56) msg="Merchant-transaction ID with value %1 is too long (max. %2 characters are allowed).";
		if (code==60) msg="nokURL is empty.";
		if (code==65) msg="okURL is empty.";
		if (code==75) msg="Serial number is empty.";
		if (code==76) msg="Serial number with value %1 is too long (max. %2 characters are allowed).";
		if (code==77) msg="Serial number %1 is not numeric.";
		if (code==80) msg="Card State %1 is invalid.";
		if (code==81) msg="Submitted Card State %1 of field %2 is not equal to the expected Card State %3.";
		if (code==85) msg="Card Type %1 is invalid.";
		if (code==90) msg="Debit State %1 is invalid.";
		if (code==95) msg="Disposition State %1 is invalid.";
		if (code==96) msg="Submitted Disposition State %1 of field %2 is not equal to the expected Disposition State %3.";
		if (code==120) msg="Close Debit-flag %1 is invalid (must be 0 or 1).";
		if (code==125) msg="Currency is empty.";
		if (code==126) msg="Currency with value %1 has invalid length (must have 3 characters).";
		if (code==140) msg="Currency Name is empty.";
		if (code==141) msg="Currency Name with value %1 is too long (max. %2 characters are allowed).";
		if (code==601) msg="The command completed successfully. - Success OK";
		if (code==602) msg="The command completed successfully; no data found. - Success OK";
		if (code==603) msg="The command completed successfully; more data match filter criteria (change filter criteria to reduce amount of data returned). - Success OK";
		if (code==1004) msg="Card with Serial Number %1 has an unexpected state %2, expected is %3. -  Card error messages";
		if (code==1005) msg="Card with Serial Number %1 has not a location %3, but is at %2. - Card error messages";
		if (code==1006) msg="Card with Serial Number %1 is not assigned to %2. - Card error messages";
		if (code==1007) msg="Card with Serial Number %1 does not exist. - Card error messages";
		if (code==1008) msg="Access denied. - Card error messages";
		if (code==1009) msg="%1 is not allowed to have Cards assigned. - Card error messages";
		if (code==1012) msg="Card State %1 is not valid for this request; expected Card State is %2. - Card error messages";
		if (code==1015) msg="Access denied because of a repeated recent access violation. - Card error messages";
		if (code==1020) msg="Challenge Question Answer 1 and Challenge Question Answer 2 are different. - Card error messages";
		if (code==1025) msg="Card is in an invalid State, expected State is GENERATED. - Card error messages";
		if (code==1026) msg="Number of copies printed is invalid; Card is set to State INVALID. - Card error messages";
		if (code==1029) msg="You need to specify question, answer and answer verification to set the Challenge Question. - Card error messages";
		if (code==1035) msg="The card status of at least one card used for this inquiry is not valid. - Card error messages";
		if (code==1046) msg="There is currently no available credit on this card; in the case of reserved amounts. - Card error messages";
		if (code==1049) msg="At least one of the PINs used is not valid. - Card error messages";
		if (code==1050) msg="Card does not exist - Card error messages";
		if (code==2001) msg="La transaction %cid/%tid ya existe. Contacte con su Tienda Virtual (Payment error messages)";
		if (code==2002) msg="La transaction %cid/%tid no existe. Contacte con su Tienda Virtual (Payment error messages)";
		if (code==2003) msg="La transaction %cid/%tid tiene el incorrecto estado %3; cuando se esperaba %4 (Payment error messages)";
		if (code==2004) msg="Fondos insuficientes para el pago; El importe de inicio es %1 (Payment error messages)";
		if (code==2006) msg="La moneda %currency es incorrecta para la transaccion %cid/%tid. Contacte con su Tienda Virtual (Payment error messages)";
		if (code==2007) msg="El importe %amount es incorrecto para la tarjeta (Payment error messages)";
		if (code==2008) msg="El importe %amount excede el saldo de la tarjeta (Payment error messages)";
		if (code==2009) msg="El importe %amount es incorrecto para la transaccion %cid/%tid. Contacte con su Tienda Virtual (Payment error messages)";
		if (code==2010) msg="El importe %amount es insuficiente para lo dispuesto en la transaccion %cid/%tid (Payment error messages)";
		if (code==2011) msg="The Currency %1 is invalid for this transaction; expected is %2. - Payment error messages";
		if (code==2012) msg="Payment transaction failed. - Payment error messages";
		if (code==2013) msg="Error finding transaction: %1. - Payment error messages";
		if (code==2014) msg="No disposition has been made for this payment transaction. - Payment error messages";
		if (code==2015) msg="Payment transaction failed. - Payment error messages";
		if (code==2016) msg="Error finding Merchant: %1. - Payment error messages";
		if (code==2017) msg="Transaction (%cid/%tid) is in invalid state %3; expected is %4 or %5. - Payment error messages";
		if (code==2018) msg="Micro Debits for transaction (%cid/%tid) are not sequential. - Payment error messages";
		if (code==2019) msg="Micro Debit for transaction (%cid/%tid) does not exist. - Payment error messages";
		if (code==2020) msg="Business type of transaction (%cid/%tid) is %3. Amount cannot be modified. - Payment error messages";
		if (code==2021) msg="The amount %amount is invalid for the transaction (%cid/%tid). The minimum transaction amount is %4. - Payment error messages";
		if (code==2022) msg="Transaction (%cid/%tid) has no cards assigned. - Payment error messages";
		if (code==2023) msg="Business type of transaction (%cid/%tid) is %3; expected: %4. Please contact your webshop. - Payment error messages";
		if (code==2024) msg="Debit cannot be performed; business type of transaction (%cid/%tid) is %3. - Payment error messages";
		if (code==2025) msg="Transaction amount is empty. Please contact your webshop. - Payment error messages";
		if (code==2026) msg="Transaction amount %amount is not numeric. Please contact your webshop. - Payment error messages";
		if (code==2027) msg="Transaction amount %amount is invalid. Please contact your webshop. - Payment error messages";
		if (code==2028) msg="Business type %1 is invalid for transaction. - Payment error messages";
		if (code==2029) msg="An error has occurred with this transaction the amount must be greater than zero. - Payment error messages";
		if (code==2039) msg="Invalid restriction parameters. - Payment error messages";
		if (code==2044) msg="Customer details requested {0} is invalid (must be 0 or 1). - Payment error messages";
		if (code==2601) msg="Payment completed successfully. - Payment OK";
		if (code==2602) msg="Command completed successfully. No transactions found. - Payment OK";
		if (code==2623) msg="Shop ID is greater than 60 characters. - Payment error messages";
		if (code==2624) msg="Shop Label is greater than 60 characters. - Payment error messages";
		if (code==3001) msg="Merchant %1 is not active. Please contact your webshop. - Master reference error message";
		if (code==3002) msg="Currency %1 is not valid for merchant %2. Please contact your webshop. - Master reference error message";
		if (code==3003) msg="Merchant %1 does not exist. Please contact your webshop. - Master reference error message";
		if (code==3006) msg="Card Type %1 is not accepted by the merchant. - Master reference error message";
		if (code==3007) msg="Merchant %1 exceeded time window to debit the transaction. - Master reference error message";
		if (code==3012) msg="Merchant %1 exceeded time window for Micropayment. - Master reference error message";
		if (code==3013) msg="Merchant %1 already exists. - Master reference error message";
		if (code==3014) msg="Reporting Criterion %1 for Merchant %2 doesnt exist. - Master reference error message";
		if (code==3015) msg="Reporting Criterion %1 for Merchant %2 is in state %3; expected %4 or %5. - Master reference error message";
		if (code==3901) msg="Feature with primary key (%1 %2 %3) cannot be found. - Feature message";
		if (code==3902) msg="The user %1 is not allowed to access the feature %2. - Feature message";
		if (code==4001) msg="SSL error. - Merchant API technical error messages";
		if (code==4002) msg="Invalid function request. - Merchant API technical error messages";
		if (code==4003) msg="Above maximum disposition amount (1,000.00 EUR or equivalent in different transaction currency). - Merchant API technical error messages";
		if (code==4004) msg="Invalid proxy request. - Merchant API technical error messages";
		if (code==4005) msg="Connection error. - Merchant API technical error messages";
		if (code==4006) msg="Unexpected response from server. - Merchant API technical error messages";
		if (code==4007) msg="Undefined error - this should not happen. - Merchant API technical error messages";
		if (code==4008) msg="Error reported from backend. - Merchant API technical error messages";
		if (code==4010) msg="Error opening configuration file. - Merchant API technical error messages";
		if (code==4011) msg="Configuration file is not a regular readable file. - Merchant API technical error messages";
		if (code==4012) msg="Incorrect syntax in configuration file. - Merchant API technical error messages";
		if (code==4013) msg="Incorrect value in configuration file. - Merchant API technical error messages";
		if (code==4014) msg="Error HTTP response from API proxy: %1. - Merchant API technical error messages";
		if (code==5001) msg="General technical error. - Technical error message";
		if (code==5002) msg="MAC check. - Technical error message";
		if (code==10003) msg="HTTPS request error. - SOPG specific error message";
		if (code==10004) msg="General technical error. - SOPG specific error message";
		if (code==10005) msg="General technical error. - SOPG specific error message";
		if (code==10006) msg="PIN validation failed. - SOPG specific error message";
		if (code==10007) msg="Unexpected error. - SOPG specific error message";
		if (code==10008) msg="Authentication failed. - SOPG specific error message";
		if (code==10010) msg="CancelPayment too late. - SOPG specific error message";
		if (code==10011) msg="Insufficient Balance. - SOPG specific error message";
		if (code==10012) msg="Zero Balance. - SOPG specific error message";
		if (code==10013) msg="Card not active. - SOPG specific error message";
		if (code==10014) msg="Method not allowed for SOPG User. - SOPG specific error message";
		if (code==10015) msg="Currency not valid for SOPG User. - SOPG specific error message"; 
		
		if (code==90001) msg="Error de conexion";
		
		msg = msg.replace("%cid", cid).replace("%tid", tid).replace("%amount", amount).replace("%currency", currency);
		
		return msg.trim();
	}
}
